#!/bin/bash
set -u

if [ $# -ne 1 ]; then
    echo "usage: $0 output-dir"
    exit 1
fi

out_dir="$1"
mkdir -p "$out_dir"

sudo ls >/dev/null

for i in $(seq 1 100); do
    sudo tcpdump -U -i docker0 -w "$out_dir/$i.pcap" 'tcp' &
    tcpdump_pid=$(ps -e | pgrep tcpdump)
    ./test_flaky $i
    sudo kill -2 $tcpdump_pid
done
